"""
Utilities for loading and preprocessing the Charades-Ego dataset for TimeSformer.
Working directly with video files.
"""

import os
import numpy as np
import torch
from datasets import load_dataset
from transformers import AutoImageProcessor
import logging
import av
import traceback

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

# --- Configuration (Adjust paths as necessary) ---
# Path to the directory containing the generated annotation files
DEFAULT_ANNOTATION_DIR = "data/CharadesEgo"  # MODIFY IF YOUR ANNOTATIONS ARE ELSEWHERE
# Path to the directory containing the video files
DEFAULT_VIDEO_BASE_PATH = "data/CharadesEgo_v1_480"  # Directory containing video files

# Assumes these files exist in DEFAULT_ANNOTATION_DIR
# TRAIN_ANNOTATION_FILE = "charadesego_train_revised_v2_grouped.txt" # Original file
TRAIN_ANNOTATION_FILE = "charadesego_train_90.txt"          # Generated by split script
VAL_ANNOTATION_FILE = "charadesego_val_revised_v2_grouped.txt"
TEST_ANNOTATION_FILE = "charadesego_test_10.txt"           # Generated by split script

# TimeSformer default config often uses 8 frames
NUM_FRAMES_TO_SAMPLE = 8
SAMPLING_RATE = 8  # Sample every 8 frames to cover longer duration, adjust as needed

def load_frames_from_video(video_path, indices):
    """
    Load specific frames from a video file.
    
    Args:
        video_path (str): Path to the video file
        indices (list): List of frame indices to load
    
    Returns:
        list: List of loaded frames as numpy arrays in RGB format, or None if loading fails
    """
    try:
        if not os.path.exists(video_path):
            logging.warning(f"Video file not found: {video_path}")
            return None
            
        with av.open(video_path) as container:
            # Get video stream
            stream = container.streams.video[0]
            
            # Calculate approximate frame count if not available in metadata
            # Some video containers don't store the frame count reliably
            if stream.frames <= 0:
                duration = stream.duration * float(stream.time_base)
                if duration <= 0 and container.duration > 0:
                    # Try container duration if stream duration is not available
                    duration = container.duration * float(av.time_base)
                
                # If we have a valid duration and frame rate, estimate the frame count
                if duration > 0 and stream.average_rate > 0:
                    total_frames = int(duration * float(stream.average_rate))
                else:
                    # Fall back to counting frames (slower but reliable)
                    logging.info(f"Counting frames manually for {video_path}")
                    frame_count = 0
                    for frame in container.decode(video=0):
                        frame_count += 1
                    total_frames = frame_count
                    # Reset container to beginning
                    container.seek(0)
            else:
                total_frames = stream.frames
                
            if total_frames <= 0:
                logging.warning(f"Could not determine frame count for {video_path}")
                return None
                
            # Ensure indices are within valid range
            if indices[-1] >= total_frames:
                logging.warning(f"Requested frame index {indices[-1]} exceeds total frames {total_frames} in {video_path}")
                indices = [min(idx, total_frames - 1) for idx in indices]
            
            # Get frame rate information
            frame_rate = stream.average_rate
            if frame_rate <= 0:
                logging.warning(f"Invalid frame rate for {video_path}, using default of 30fps")
                frame_rate = 30.0
                
            frames = []
            
            # Simple method for direct frame extraction
            if len(indices) <= 8:  # For a small number of frames, use the direct method
                for idx in indices:
                    # Calculate timestamp in seconds
                    timestamp = float(idx) / float(frame_rate)
                    
                    # Seek to the timestamp
                    container.seek(int(timestamp * av.time_base), stream=stream)
                    
                    # Read and decode frame
                    frame_found = False
                    for frame in container.decode(video=0):
                        # Convert AVFrame to numpy array (RGB format)
                        img = frame.to_ndarray(format='rgb24')
                        frames.append(img)
                        frame_found = True
                        break  # Only take the first frame after seeking
                        
                    if not frame_found:
                        logging.warning(f"Could not find frame at index {idx} in {video_path}")
                        if frames:  # If we already have some frames, duplicate the last one
                            frames.append(frames[-1])
            else:
                # More robust method for larger indices - decode all frames and select the ones we need
                frame_idx = 0
                indices_set = set(indices)
                for frame in container.decode(video=0):
                    if frame_idx in indices_set:
                        img = frame.to_ndarray(format='rgb24')
                        frames.append(img)
                        
                        # If we've collected all frames, we can stop
                        if len(frames) == len(indices):
                            break
                    frame_idx += 1
            
            # Check if we have all the frames
            if len(frames) != len(indices):
                logging.warning(f"Could only load {len(frames)} out of {len(indices)} requested frames from {video_path}")
                # If at least some frames were loaded, duplicate the last frame to reach the desired count
                if frames:
                    while len(frames) < len(indices):
                        frames.append(frames[-1])
                else:
                    return None
                    
            return frames
            
    except Exception as e:
        logging.error(f"Error loading frames from {video_path}: {e}")
        logging.error(traceback.format_exc())
        return None

def sample_frame_indices(total_frames, frame_sample_rate, seg_len):
    """
    Sample a given number of frame indices. Handles edge cases.
    Args:
        total_frames (int): Total number of frames available. Must be > 0.
        frame_sample_rate (int): Sample every N frames. Must be >= 1.
        seg_len (int): Number of frames to sample. Must be > 0.
    Returns:
        list: List of sampled frame indices
    """
    if total_frames <= 0 or frame_sample_rate < 1 or seg_len <= 0:
        logging.error(f"Invalid input to sample_frame_indices: total_frames={total_frames}, frame_sample_rate={frame_sample_rate}, seg_len={seg_len}")
        return []

    # Calculate the effective number of frames considering the sampling rate
    converted_len = max(1, total_frames // frame_sample_rate)

    if converted_len < seg_len:
        # If not enough frames after sampling, sample with repeats
        indices = np.linspace(0, total_frames - 1, seg_len)
        indices = np.clip(indices, 0, total_frames - 1).astype(int)
    else:
        # Sample uniformly from the 'rate-adjusted' indices, then scale back
        end_idx = converted_len - 1
        indices = np.linspace(0, end_idx, seg_len, dtype=int)
        indices = indices * frame_sample_rate
        indices = np.clip(indices, 0, total_frames - 1).astype(int)

    return sorted(indices)

def get_video_frame_count(video_path):
    """
    Get the total number of frames in a video file.
    Args:
        video_path (str): Path to the video file
    Returns:
        int: Total number of frames or 0 if video couldn't be opened
    """
    try:
        if not os.path.exists(video_path):
            return 0
            
        with av.open(video_path) as container:
            stream = container.streams.video[0]
            
            # First, try to get frame count from metadata
            if stream.frames > 0:
                return stream.frames
                
            # If not available, estimate from duration and frame rate
            duration = stream.duration * float(stream.time_base)
            if duration <= 0 and container.duration > 0:
                # Try container duration if stream duration is not available
                duration = container.duration * float(av.time_base)
            
            if duration > 0 and stream.average_rate > 0:
                return int(duration * float(stream.average_rate))
                
            # As a last resort, count frames (slower but reliable)
            logging.info(f"Counting frames manually for {video_path}")
            frame_count = 0
            for frame in container.decode(video=0):
                frame_count += 1
            return frame_count
                
    except Exception as e:
        logging.error(f"Error getting frame count for {video_path}: {e}")
        logging.error(traceback.format_exc())
        return 0

def load_charades_ego_splits(annotation_dir=DEFAULT_ANNOTATION_DIR, video_base_path=DEFAULT_VIDEO_BASE_PATH):
    """
    Loads the grouped Charades-Ego annotations (using the 90/10 split for train/test)
    and creates Hugging Face Datasets.
    Adds the full video file path to each entry.
    """
    train_ann_path = os.path.join(annotation_dir, TRAIN_ANNOTATION_FILE)
    val_ann_path = os.path.join(annotation_dir, VAL_ANNOTATION_FILE)
    test_ann_path = os.path.join(annotation_dir, TEST_ANNOTATION_FILE)

    data_files = {}
    if not os.path.exists(train_ann_path):
        logging.warning(f"Training annotation file ({TRAIN_ANNOTATION_FILE}) not found at {train_ann_path}.")
        logging.warning("Did you run the 'scripts/split_train_test.sh' script?")
        # Optionally fall back to the original file if the split one doesn't exist
        original_train_path = os.path.join(annotation_dir, "charadesego_train_revised_v2_grouped.txt")
        if os.path.exists(original_train_path):
            logging.warning(f"Falling back to original training file: {original_train_path}")
            train_ann_path = original_train_path
            data_files["train"] = train_ann_path
        else:
            raise FileNotFoundError(f"Neither split training file ({TRAIN_ANNOTATION_FILE}) nor original training file found in {annotation_dir}")
    else:
        data_files["train"] = train_ann_path

    if not os.path.exists(val_ann_path):
        raise FileNotFoundError(f"Validation annotation file not found: {val_ann_path}")
    data_files["validation"] = val_ann_path

    # Conditionally add test split if the file exists
    if os.path.exists(test_ann_path):
        logging.info(f"Found test annotation file: {test_ann_path}")
        data_files["test"] = test_ann_path
    else:
        logging.warning(f"Test annotation file ({TEST_ANNOTATION_FILE}) not found at {test_ann_path}. Test split will not be loaded.")
        logging.warning("Did you run the 'scripts/split_train_test.sh' script?")

    logging.info(f"Loading datasets from: {annotation_dir} using files: {data_files}")
    dataset = load_dataset("text", data_files=data_files)

    def split_line(example):
        parts = example["text"].strip().split()
        if len(parts) == 2:
            return {"video_id": parts[0], "label_str": parts[1]}
        else:
            logging.warning(f"Skipping malformed line: {example['text']}")
            return {"video_id": None, "label_str": None}

    dataset = dataset.map(split_line, remove_columns=["text"], num_proc=os.cpu_count())
    dataset = dataset.filter(lambda example: example["video_id"] is not None, num_proc=os.cpu_count())

    def cast_label(example):
        try:
            return {"label": int(example["label_str"])}
        except (ValueError, TypeError):
            logging.warning(f"Could not cast label to int: {example['label_str']} for video {example['video_id']}")
            return {"label": -1}

    dataset = dataset.map(cast_label, remove_columns=["label_str"], num_proc=os.cpu_count())
    dataset = dataset.filter(lambda example: example["label"] != -1, num_proc=os.cpu_count())

    def add_video_path(example):
        video_id = example["video_id"]
        # Try multiple video extensions (mp4, avi, mov)
        for ext in ["mp4", "avi", "mov"]:
            video_path = os.path.join(video_base_path, f"{video_id}.{ext}")
            if os.path.exists(video_path):
                # Get the frame count for the video
                total_frames = get_video_frame_count(video_path)
                if total_frames > 0:
                    return {
                        "video_path": video_path,
                        "total_frames": total_frames
                    }
        
        # If no valid video file was found
        return {
            "video_path": None,
            "total_frames": 0
        }

    # Add video paths and remove video_id since we don't need it anymore
    dataset = dataset.map(add_video_path, remove_columns=["video_id"], num_proc=os.cpu_count())
    
    # Filter out examples where videos weren't found
    initial_counts = {split: len(dataset[split]) for split in dataset.keys()}

    dataset = dataset.filter(
        lambda example: example["video_path"] is not None and example["total_frames"] > 0,
        num_proc=os.cpu_count()
    )

    final_counts = {split: len(dataset[split]) for split in dataset.keys()}

    for split in initial_counts:
        removed_count = initial_counts[split] - final_counts[split]
        if removed_count > 0:
            logging.warning(f"Removed {removed_count} {split} examples due to missing videos.")

    logging.info(f"Dataset loaded: {dataset}")
    logging.info(f"Final counts per split: {final_counts}")
    return dataset

class VideoPreprocessor:
    """
    A callable class to preprocess video frames for TimeSformer.
    Uses the provided Hugging Face image processor.
    """

    def __init__(self, image_processor, num_frames=NUM_FRAMES_TO_SAMPLE, sample_rate=SAMPLING_RATE):
        self.image_processor = image_processor
        self.num_frames = num_frames
        self.sample_rate = sample_rate
        logging.info(f"VideoPreprocessor initialized with num_frames={num_frames}, sample_rate={sample_rate}")

    def __call__(self, examples):
        """
        Processes a batch of examples.
        Loads frames directly from videos, samples them, and applies processor transformations.
        Returns tensors suitable for model input.
        """
        # Get video_path and total_frames, ensure they're lists
        video_paths = examples["video_path"]
        total_frames = examples["total_frames"]
        if not isinstance(video_paths, list):
            video_paths = [video_paths]
            total_frames = [total_frames]

        labels = examples["label"]
        if not isinstance(labels, list):
            labels = [labels]

        processed_pixel_values = []
        processed_labels = []

        for video_path, num_frames, label in zip(video_paths, total_frames, labels):
            try:
                if video_path is None or num_frames == 0:
                    logging.warning("Skipping example with invalid video path or zero frames")
                    continue

                indices = sample_frame_indices(
                    total_frames=num_frames,
                    frame_sample_rate=self.sample_rate,
                    seg_len=self.num_frames
                )
                
                if not indices:
                    logging.warning(f"Frame sampling failed for {video_path}. Skipping.")
                    continue

                frames = load_frames_from_video(video_path, indices)
                
                if frames is None:
                    logging.warning(f"Could not load required frames from {video_path}. Skipping.")
                    continue

                # Apply image processor - the processor can handle numpy arrays
                processor_inputs = self.image_processor(images=frames, return_tensors="pt")
                processed_pixel_values.append(processor_inputs["pixel_values"].squeeze(0))
                processed_labels.append(label)

            except Exception as e:
                logging.error(f"Unexpected error processing video {video_path}: {e}")
                continue

        if not processed_pixel_values:
            return {"pixel_values": torch.empty(0), "label": torch.empty(0, dtype=torch.long)}

        try:
            batch_pixel_values = torch.stack(processed_pixel_values)
            batch_labels = torch.tensor(processed_labels, dtype=torch.long)
        except Exception as e:
            logging.error(f"Error stacking tensors for batch: {e}")
            return {"pixel_values": torch.empty(0), "label": torch.empty(0, dtype=torch.long)}

        return {"pixel_values": batch_pixel_values, "label": batch_labels}

if __name__ == "__main__":
    # --- Example Usage ---
    logging.info("Starting data utils example...")

    MODEL_ID = "facebook/timesformer-base-finetuned-k400"
    try:
        image_processor = AutoImageProcessor.from_pretrained(MODEL_ID, use_fast=True)
    except Exception as e:
        logging.error(f"Failed to load image processor for {MODEL_ID}: {e}")
        exit()

    try:
        # Load datasets (will now include 'test' if available)
        charades_dataset = load_charades_ego_splits()
    except FileNotFoundError as e:
        logging.error(f"Dataset loading failed: {e}")
        logging.warning("Please ensure annotation files exist at expected paths or adjust DEFAULT_ANNOTATION_DIR.")
        logging.warning(f"Looked for: {os.path.join(DEFAULT_ANNOTATION_DIR, TRAIN_ANNOTATION_FILE)}, {os.path.join(DEFAULT_ANNOTATION_DIR, VAL_ANNOTATION_FILE)}, and potentially {os.path.join(DEFAULT_ANNOTATION_DIR, TEST_ANNOTATION_FILE)}")
        logging.warning("If using split files, ensure 'scripts/split_train_test.sh' has been run.")
        exit()
    except Exception as e:
        logging.error(f"An unexpected error occurred during dataset loading: {e}")
        exit()

    preprocessor = VideoPreprocessor(image_processor)

    try:
        charades_dataset.set_transform(preprocessor)
        logging.info("Dataset transform set. Accessing elements will now apply preprocessing.")

        # Display info for each available split
        for split_name in charades_dataset.keys():
            if len(charades_dataset[split_name]) > 0:
                logging.info(f"--- {split_name.upper()} Split --- ")
                example_element = charades_dataset[split_name][0]
                logging.info(f"Processed element keys: {example_element.keys()}")
                logging.info(f"Pixel values shape: {example_element['pixel_values'].shape}")
                logging.info(f"Label: {example_element['label']}")

                logging.info(f"Pixel values type: {type(example_element['pixel_values'])}")
                logging.info(f"Pixel values dtype: {example_element['pixel_values'].dtype}")
                logging.info(f"Label type: {type(example_element['label'])}")
                logging.info(f"Label dtype: {example_element['label'].dtype}")

            else:
                logging.warning(f"No examples found in {split_name} split.")

    except Exception as e:
        logging.error(f"Error during preprocessing test using set_transform: {e}")

    logging.info("Data utils example finished.")
